# Engine runtime configuration

[window]
title = Engine
width = 1280
height = 720
resizable = false

[vulkan]
application_name = Engine
application_version_major = 1
application_version_minor = 0
application_version_patch = 0
engine_name = LearningEngine
engine_version_major = 1
engine_version_minor = 0
engine_version_patch = 0

[render]
clear_r = 0.12
clear_g = 0.42
clear_b = 0.55
clear_a = 1.0

[runtime]
print_startup_summary = false
print_first_frame_message = false

[render_loop]
prefer_vsync = true
prefer_mailbox_present_mode = true

[paths]
shader_root = shaders
asset_root = assets
cache_root = cache
